#!/usr/bin/php
<?
# Call this script from the root of your project (like "modulekit/build_cache")

# First clean old cache
@mkdir(".modulekit-cache");
unlink(".modulekit-cache/globals");

# Call the loader, which sets a couple of globals
include "loader.php";

# Write variable to globals
file_put_contents(".modulekit-cache/globals", serialize($modulekit));
